language: node_js
node_js:
  - lts/*
jobs:
  include:
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
        on:
          branch: master
